name: Daily VLS Tracker

on:
  schedule:
    - cron: '0 12 * * *'   # 8AM ET daily (12 PM UTC)
  workflow_dispatch:       # Manual run option

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker script
        run: python main.py
