name: Daily VLS Tracker

on:
  schedule:
    - cron: '0 12 * * *'   # Runs daily at 12:00 UTC (8 AM ET)
  workflow_dispatch:       # Allow manual trigger

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker script
        run: python main.py

      - name: Commit updated CSV files to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/listing_first_seen.csv
          git add data/VLS\ expired*.csv || echo "No expired files to add"
          if ! git diff --cached --quiet; then
            git commit -m "Update listing_first_seen.csv and expired listings from daily VLS tracker"
            git push
          else
            echo "No changes to commit."
          fi
