name: Daily VLS Tracker

on:
  schedule:
    - cron: '0 1 * * *'   # Runs daily at 1 AM UTC
  workflow_dispatch:       # Enables manual run from GitHub UI

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker script
        run: python main.py

      - name: Commit updated tracking file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/listing_first_seen.csv
          git commit -m "Update tracking database [skip ci]" || echo "No changes to commit"
          git push
